### ISSUE TITLE
vagrant up時にエラーが表示されていた．

### ISSUE THREAD

**Issue by yudmo** [chiemi627/enpitut_webenv#4]
`vagrant up`時にエラーが表示され，`vagrant ssh`時にpasswordが要求された

---

解決策として，SSHで使用する鍵に問題があり，`curl -L https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub -o /home/vagrant/.ssh/authorized_keys`で解決できました．

**Comment by chiemi627** [comment]
初歩的なミスでした！連絡ありがとう。
すぐ対応します。

**Comment by chiemi627** [comment]
上記の対応をした virtualbox ファイルを vagrantcloud にアップしました。
